name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ["self-hosted", "custom-runner"]
    container:
      image: node:latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          #ls ${{ github.workspace }}
          npm install
      - name: test
        id: test
        continue-on-error: true
        run: |
          #ls ${{ github.workspace }}
          exit 1
      - run: echo "ğŸ This job's status is ${{ steps.test.outcome }}."
        if: steps.test.outcome != 'success'
